apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
  namespace: default
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
